import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from src.models.equal_weight import train_equal_weight
from src.models.simplex_optimizer import (
    train_lasso,
    plot_lasso_sweep
)
from src.models.sparse_autoencoder import train_sae

plt.style.use('seaborn-v0_8-whitegrid')

TARGET = '^SP500TR'

# =========================================================
# Utilities
# =========================================================

def ensure_directories():
    os.makedirs('models', exist_ok=True)
    os.makedirs('plots', exist_ok=True)


# =========================================================
# Load Pre-Processed Datasets
# =========================================================

def load_preprocessed_data():
    print("Loading datasets generated by features.py...")

    # ----------------------------------------
    # Scaled datasets (For Neural Network)
    # ----------------------------------------
    X_train_scaled = pd.read_csv("data/X_train_scaled.csv", index_col=0, parse_dates=True)
    X_val_scaled = pd.read_csv("data/X_val_scaled.csv", index_col=0, parse_dates=True)

    # ----------------------------------------
    # Unscaled datasets (For Physical Allocation)
    # ----------------------------------------
    X_train_unscaled = pd.read_csv("data/X_train_unscaled.csv", index_col=0, parse_dates=True)
    X_val_unscaled = pd.read_csv("data/X_val_unscaled.csv", index_col=0, parse_dates=True)

    # ----------------------------------------
    # Targets
    # ----------------------------------------
    y_train = pd.read_csv("data/y_train.csv", index_col=0).squeeze()
    y_val = pd.read_csv("data/y_val.csv", index_col=0).squeeze()

    print(f"  Train rows : {len(X_train_scaled)}")
    print(f"  Val rows   : {len(X_val_scaled)}")

    return (
        X_train_scaled,
        X_val_scaled,
        X_train_unscaled,
        X_val_unscaled,
        y_train,
        y_val
    )


# =========================================================
# Visualization
# =========================================================

def plot_instrument_weights(weights_df: pd.DataFrame):
    print("Generating Plot 5: Instrument Weight Allocations...")

    fig, ax = plt.subplots(figsize=(14, 6))

    # FIX: Restored the exact color mapping to match the line charts
    weights_df.plot(
        kind='bar',
        ax=ax,
        width=0.8,
        color=['steelblue', 'darkorange', 'seagreen']
    )

    ax.set_title("Frozen Portfolio Allocation Vectors (Plot 5)", fontsize=14, fontweight='bold')
    ax.set_ylabel("Portfolio Weight")
    ax.set_xlabel("Assets")
    ax.grid(axis='y', alpha=0.3)
    ax.legend(title='Replication Models')

    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()

    plt.savefig("plots/05_instrument_weights.png", dpi=150, bbox_inches='tight')
    plt.close()


# =========================================================
# Main Pipeline
# =========================================================

def run_models_pipeline():
    print("\n--- Starting Milestone 3: Model Training & Feature Extraction ---")
    ensure_directories()

    (
        X_train_scaled,
        X_val_scaled,
        X_train_unscaled,
        X_val_unscaled,
        y_train,
        y_val
    ) = load_preprocessed_data()

    # =====================================================
    # MODEL B: Elastic Net (The Sparsity Anchor)
    # Uses UNSCALED returns to solve physical weights
    # =====================================================
    (
        lasso_weights,
        alphas,
        tracking_errors,
        asset_counts,
        best_alpha
    ) = train_lasso(
        X_train_unscaled,
        y_train,
        X_val_unscaled,
        y_val
    )

    plot_lasso_sweep(alphas, tracking_errors, asset_counts, best_alpha)

    # Determine the mathematically optimal K
    active_assets_count = (lasso_weights > 0).sum()
    print(f"\n[!] APPLES-TO-APPLES CONSTRAINT: Lasso determined {active_assets_count} assets is optimal.")
    print(f"[!] Forcing Equal-Weight and SAE to allocate across exactly {active_assets_count} assets.\n")

    # =====================================================
    # MODEL A: Equal Weight (The Baseline)
    # Uses UNSCALED returns
    # =====================================================
    # FIX: Updated signature to match the refactored equal_weight.py
    eq_weights = train_equal_weight(
        X_train_unscaled,
        y_train,
        X_val_unscaled,
        y_val,
        top_k=active_assets_count
    )

    # =====================================================
    # MODEL C: Sparse Autoencoder (The Deep Network)
    # Uses SCALED features to prevent variance-driven learning
    # =====================================================
    sae_weights = train_sae(
        X_train_scaled,
        y_train,
        X_val_scaled,
        y_val,
        top_k=active_assets_count
    )

    # =====================================================
    # Freeze Weights
    # =====================================================
    print("Compiling and freezing structurally identical portfolio vectors...")
    frozen_weights = pd.DataFrame({
        'Equal_Weight': eq_weights,
        'Lasso': lasso_weights,
        'SAE': sae_weights
    }).fillna(0.0)

    # Drop assets that all models ignored
    frozen_weights = frozen_weights.loc[(frozen_weights != 0).any(axis=1)]
    frozen_weights.to_csv("models/frozen_weights_2022.csv")

    plot_instrument_weights(frozen_weights)

    print("Milestone 3 Complete. Portfolios frozen and ready for Backtesting.\n")